export const MAIN_PATH = "/";
export const TRANSFER_PATH = "/transfer";
export const TRANSFERS_PATH = "/transfers";
export const ADD_PATH = "/add";
export const SEARCH_PATH = "/q";
export const EDIT_PATH = "/edit";
export const DELETE_PATH = "/delete";
export const ADD_TRANSFER_PATH = "/add-transfer";
export const BUS_PATH = "/bus";
export const CONTACTS_PATH = "/contacts";
export const TRANSFERS_SEARCH_PATH = `${TRANSFERS_PATH}${SEARCH_PATH}`;
export const TRANSFERS_ADD_TRANSFER_PATH = `${TRANSFERS_PATH}${ADD_TRANSFER_PATH}`;
export const TRIP_EDIT_PATH = `${TRANSFER_PATH}${EDIT_PATH}`;
export const TRIP_DELETE_PATH = `${TRANSFER_PATH}${DELETE_PATH}`;

export const ROMAN_PHONE_NUMBER = "+972 54-577-9239";
export const ROMAN_EMAIL = "roman.mantelmakher@gmail.com";
export const MAX_PAGE_SIZE = 12;
export const TIMESTAMP_FIELD = "_timestamp";
