export const currencies = [
  {"name":"Euro","code":"EUR","oneEuroRate":1.0,"r2rSymbol":"€"},
  {"name":"United States Dollar","code":"USD","oneEuroRate":1.17628,"r2rSymbol":"$"},
  {"name": "Russia Ruble", "code": "RUB", "oneEuroRate": 86.2976, "r2rSymbol": "₽"},
  {"name":"Ukraine Hryvnia","code":"UAH","oneEuroRate":31.547,"r2rSymbol":"грн"},
  {"name":"Belarus Ruble","code":"BYN","oneEuroRate":2.95558,"r2rSymbol":"Br"},
  // {"name":"Israel Shekel","code":"ILS","oneEuroRate":3.79445,"r2rSymbol":"₪"},
  // {"name":"India Rupee","code":"INR","oneEuroRate":87.3294,"r2rSymbol":"₹"},
  {"name":"Poland Zloty","code":"PLN","oneEuroRate":4.57397,"r2rSymbol":"zł"},
  {"name":"Czech Republic Koruna","code":"CZK","oneEuroRate":25.4098,"r2rSymbol":"Kč"},
  {"name":"Romania Leu","code":"RON","oneEuroRate":4.91368,"r2rSymbol":"L"},
  {"name":"Bulgaria Lev","code":"BGN","oneEuroRate":1.95626,"r2rSymbol":"лв."},
  {"name":"Hungary Forint","code":"HUF","oneEuroRate":353.896,"r2rSymbol":"Ft"},
  {"name":"Turkey Lira","code":"TRY","oneEuroRate":10.1526,"r2rSymbol":"TL"},
  {"name":"Croatia Kuna","code":"HRK","oneEuroRate":7.49902,"r2rSymbol":"kn"},
];